integrated JSLint into build

diff --git a/publish b/publish
--- a/publish
+++ b/publish
@@ -18,6 +18,12 @@ rm -f examples/*.pyc
 cp -R examples build/
 cp .htaccess build/
 
+echo "linting JS"
+
+[ -n "$(which js 2>/dev/null)" ] || die "SpiderMonkey (js or js.exe) not found"
+js_lint_results=`js j/jslint.js < build/j/dip3.js 2>/dev/null`
+[ "$js_lint_results" = "jslint: No problems found." ] || die "$js_lint_results"
+
 echo "minimizing HTML"
 
 # minimize HTML (NB: this script is quite fragile and relies on knowledge of how I write HTML)
